# Generated by Django 6.0.6 on 2026-06-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_demorequest_user_eventregistration_user_inquiry_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('visits', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'page_visits',
                'ordering': ['-date'],
            },
        ),
    ]
