# Generated by Django 6.0.6 on 2026-06-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pagevisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='demorequest',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
