# Generated by Django 5.2.15 on 2026-06-28 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='experience',
            field=models.TextField(blank=True, default=''),
        ),
    ]
