# Generated by Django 5.2.15 on 2026-06-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_jobapplication_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='resume',
            field=models.TextField(blank=True, default=''),
        ),
    ]
