# Generated by Django 5.2.15 on 2026-06-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_jobapplication_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demorequest',
            name='company',
        ),
        migrations.RemoveField(
            model_name='eventregistration',
            name='company',
        ),
        migrations.AlterField(
            model_name='demorequest',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='attendee_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
