# Generated by Django 5.2.15 on 2026-06-28 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='experience',
        ),
    ]
