# Generated by Django 5.2.15 on 2026-06-28 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_feedback_new_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='event_attended',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='message',
        ),
    ]
