# Generated by Django 5.2.15 on 2026-06-28 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_user_fk_job_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='status',
        ),
    ]
