# Generated by Django 5.2.15 on 2026-06-30 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_feedback_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobApplication',
        ),
    ]
